studentsdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from .settings import MEDIA_ROOT, DEBUG
from students.views.student import StudentUpdateView, StudentDeleteView
from students.views.group import GroupCreateView, GroupUpdateView, GroupDeleteView
from students.views.journal import JournalView
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from students.views.group import groups_list
js_info_dict = {
'packages': ('students',),
}

urlpatterns = [
    #Students urls
    url(r'^students/add/$', 'students.views.student.students_add', name='students_add'),
    url(r'^students/(?P<pk>[0-9]+)/edit/$',  StudentUpdateView.as_view(), name='students_edit'),
	url(r'^students/(?P<sid>[0-9]+)/visiting/$', 'students.views.student.students_visiting', name='students_visiting'),  
    url(r'^students/(?P<pk>[0-9]+)/delete/$', StudentDeleteView.as_view(), name='students_delete'),
    #Groups
    url(r'^groups/$', login_required(groups_list), name='groups_list'),
    url(r'^groups/add/$', login_required(GroupCreateView.as_view()), name='group_add'),
    url(r'^groups/(?P<pk>[0-9]+)/edit/$', login_required(GroupUpdateView.as_view()), name='group_edit'),
    url(r'^groups/(?P<pk>[0-9]+)/delete/$', login_required(GroupDeleteView.as_view()), name='group_delete'),
    #Journal
    url(r'^journal/(?P<pk>\d+)?/?$', JournalView.as_view(), name='journal'),
    url(r'^admin/', include(admin.site.urls)),
    #debug media 
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT,}),
    #auth
    url(r'^user/profile/$', login_required(TemplateView.as_view(
        template_name='registration/profile.html')), name = 'profile'),
    url(r'^user/logout/$',auth_views.logout, kwargs = {'next_page': 'home'}, name = 'auth_logout'),
    url(r'^register/complete/$',RedirectView.as_view(pattern_name = 'home'), name = 'registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls', namespace = 'users')),
    #social auth
    url(r'^social/', include('social.apps.django_app.urls', namespace='social')),
    
    url(r'^contact-admin/$', 'students.views.contact_admin.contact_admin', name='contact_admin'),
    url(r'^jsi18n\.js$', 'django.views.i18n.javascript_catalog', js_info_dict),
    #------
    url(r'^', 'students.views.student.student_list', name='home'),

] 

students/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.
class Student(models.Model):
	"""Student Model"""
	class Meta(object):
		verbose_name=_(u'Student')
		verbose_name_plural=_(u'Students')

	first_name =models.CharField(max_length=256, blank=False, verbose_name=_(u'Name'))
	last_name = models.CharField(max_length=256, blank=False, verbose_name=_(u'Last Name'))
	middle_name = models.CharField(max_length=256, blank=True, verbose_name=_(u'Middle Name'), default='')
	birthday = models.DateField(blank=False, verbose_name=_(u'Birthday'))
	photo = models.ImageField(blank=True, verbose_name=_(u'Photo'))
	ticket = models.CharField(max_length=256, blank=False, verbose_name='Ticket')
	student_group = models.ForeignKey('Group',
		verbose_name=_(u'Group'), 
		blank=True, null=True, on_delete=models.PROTECT)
	notes = models.TextField(blank=True, verbose_name=_(u'Notes'), default='')

	def __str__(self):
		return u'%s %s' % (self.first_name, self.last_name)

class Group(models.Model):
	"""docstring for Group"""
	class Meta(object):
		verbose_name=_(u'Group')
		verbose_name_plural=_(u'Groups')

	title =models.CharField(max_length=256, blank=False, verbose_name=_(u'Title'))
	notes = models.TextField(blank=True, verbose_name=_(u'Notes'), default='')	
	leader = models.OneToOneField('Student',
	verbose_name=_(u'Leader'),
	blank=True,
	null=True,
	on_delete = models.SET_NULL)
	def __str__(self):
		return u'%s' % (self.title)

class MonthJournal(models.Model):
	class Meta(object):
		verbose_name=_(u'MonthJournal')
		verbose_name_plural=_(u'MonthJournals')

	student = models.ForeignKey('Student', verbose_name=_(u'Student'),blank = False, unique_for_month='date')
	date = models.DateField(verbose_name=_(u'Date'), blank=False)
	
	present_day1 = models.BooleanField(default=False)
	present_day2 = models.BooleanField(default=False)
	present_day3 = models.BooleanField(default=False)
	present_day4 = models.BooleanField(default=False)
	present_day5 = models.BooleanField(default=False)
	present_day6 = models.BooleanField(default=False)
	present_day7 = models.BooleanField(default=False)
	present_day8 = models.BooleanField(default=False)
	present_day9 = models.BooleanField(default=False)
	present_day10 = models.BooleanField(default=False)
	present_day11 = models.BooleanField(default=False)
	present_day12 = models.BooleanField(default=False)
	present_day13 = models.BooleanField(default=False)
	present_day14 = models.BooleanField(default=False)
	present_day15 = models.BooleanField(default=False)
	present_day16 = models.BooleanField(default=False)
	present_day17 = models.BooleanField(default=False)
	present_day18 = models.BooleanField(default=False)
	present_day19 = models.BooleanField(default=False)
	present_day20 = models.BooleanField(default=False)
	present_day21 = models.BooleanField(default=False)
	present_day22 = models.BooleanField(default=False)
	present_day23 = models.BooleanField(default=False)
	present_day24 = models.BooleanField(default=False)
	present_day25 = models.BooleanField(default=False)
	present_day26 = models.BooleanField(default=False)
	present_day27 = models.BooleanField(default=False)
	present_day28 = models.BooleanField(default=False)
	present_day29 = models.BooleanField(default=False)
	present_day30 = models.BooleanField(default=False)
	present_day31 = models.BooleanField(default=False)

	def __str__(self):
		return u'%s: %d, %d' % (self.student.last_name, self.date.month,
            self.date.year)

students/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http.response import HttpResponse
from django.template import RequestContext
# Create your views here.
def home(request):
	students = (
		{'id': 1,
		'first_name': 'Сергей',
		'last_name':'Нелепа',
		'ticket':1,
		'image':'static/img/me2.jpg'
		},
		{'id': 2,
		'first_name': 'Сергей',
		'last_name':'Нелепа',
		'ticket':11,
		'image':'static/img/me2.jpg'
		},
		{'id': 3,
		'first_name': 'Сергей',
		'last_name':'Нелепа',
		'ticket':12,
		'image':'static/img/me2.jpg'
		},
	)
	groups = ({'name':'mf111'}, {'name':'mf112'}, {'name':'mf113'})
	return render(request, 'students/students_list.html', {"students": students, "groups": groups})

def students_add(request):
	return HttpResponse('here will be form students')

def students_edit(request, sid):
	return HttpResponse('here will be form students %s' % sid)

def students_visiting(request, sid):
	return HttpResponse('visiting %s' % sid)

def students_delete(request, sid):
	return HttpResponse('delete %s' % sid)

def groups_list(request):
	groups = ({
		'id':1,
		'name':'mf131',
		'steward': { 'id' : 1, 'name' : 'Нелепа Сергей'}
		},
		{
		'id':2,
		'name':'mf132',
		'steward': { 'id' : 2, 'name' : 'Сопельник Юлия'}
		},
		)
	return render(request, 'students/groups_list.html', {"groups": groups})
def groups_edit(request, sid):
	return HttpResponse('group edit %s'% sid)

def groups_delete(request, sid):
	return HttpResponse('group delete %s'% sid)

def journal(request):
	return HttpResponse('here will be journal')

students/views/contact_admin.py
# -*- coding: utf-8 -*-
import logging
from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from studentsdb.settings import ADMIN_EMAIL
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import permission_required

class ContactForm(forms.Form):
	
	def __init__(self, *args, **kwargs):
		super(ContactForm, self).__init__(*args, **kwargs)
		# this helper object allows us to customize form
		self.helper = FormHelper()
		# form tag attributes
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = reverse('contact_admin')
		# twitter bootstrap styles
		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-2 control-label'
		self.helper.field_class = 'col-sm-4'
		# form buttons
		self.helper.add_input(Submit('send_button', _(u'Send')))
	
	from_email = forms.EmailField(label=_(u"You e-mail"))
	
	subject = forms.CharField(label=_(u"Title"),max_length=128)
	
	message = forms.CharField(label=_(u"Text message"),max_length=2560,
	widget=forms.Textarea)

@permission_required('auth.add_user')
def contact_admin(request):
    # check if form was posted
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)

        # check whether user data is valid:
        if form.is_valid():
            # send email
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']

            try:
                send_mail(subject, message, from_email, [ADMIN_EMAIL])
            except Exception:
                message = _(u'When you send a letter to an unexpected error occurred. Try this form later.')
                logger = logging.getLogger(__name__)
                logger.exception(message)
            else:
                message = _(u'Message sent successfully!')

            # redirect to same contact page with success message
            return HttpResponseRedirect(
                u'%s?status_message=%s' % (reverse('contact_admin'), message))

    # if there was not POST render blank form
    else:
        form = ContactForm()

    return render(request, 'contact_admin/form.html', {'form': form})

students/views/group.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from students.models import Group
from django.core.paginator  import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import UpdateView, DeleteView, CreateView
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FormActions
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _


def groups_list(request):
    groups = Group.objects.all()
    paginator = Paginator(groups, 5)
    page = request.GET.get('page')
    try:
        groups = paginator.page(page)
    except PageNotAnInteger:
        groups = paginator.page(1)
    except EmptyPage:
        groups = paginator.page(paginator.num_pages)
    return render(request, 'students/groups_list.html', {"groups": groups})


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

        if kwargs['instance'] is None:
            add_form = True
        else:
            add_form = False
        # set form tag attributes
        if add_form:
            self.helper.form_action = reverse('group_add')
        else:
            self.helper.form_action = reverse('group_edit', kwargs={'pk': kwargs['instance'].id})

        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'
        # set form field properties
        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'
        # add buttons
        # self.helper.layout[-1] = FormActions(
        # Submit('add_button', u'Save', css_class="btn btn-primary"),
        # Submit('cancel_button', u'Cancel', css_class="btn btn-link"),)
        self.helper.add_input(Submit('add_button', _(u'Save')))
        self.helper.add_input(Submit('cancel_button', _(u'Cancel')))

class BaseGroupView(object):
    def get_success_url(self):
        return u'%s?status_message=%s'% (reverse('groups_list'), _(u'Group has been saved!'))

    def post(self, request, *args, **kwargs):
        # handle cancel button
        if request.POST.get('cancel_button'):
            return HttpResponseRedirect(reverse('groups_list') +_(u'?status_message=Editing canceled.'))
        else:
            return super(BaseGroupView, self).post(request, *args, **kwargs)

class GroupCreateView(BaseGroupView,CreateView):
    model = Group
    template_name = 'groups/groups_add.html'
    form_class = GroupForm


class GroupUpdateView(BaseGroupView,UpdateView):
    model = Group
    template_name = 'groups/groups_add.html'
    form_class = GroupForm

class GroupDeleteView(DeleteView):
    model = Group
    template_name = 'groups/group_confirm_delete.html'

    def get_success_url(self):
        #return '/'
        #return u'%s/?status_message=Student has been saved!'% reverse('home')
        return u'%s?status_message=%s' % (reverse('groups_list'), _(u"Group has been deleted!"))

		# def post(self, request, *args, **kwargs):
		# 	try:
		# 		return HttpResponseRedirect(reverse('groups_list') +u'?status_message=Group deleting.')
		# 	except:
		# 		return HttpResponseRedirect(reverse('groups_list') +u'?status_message=Group deleting error.')

students/views/journal.py
from django.views.generic.base import TemplateView
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from calendar import monthrange, weekday, day_abbr
from django.core.urlresolvers import reverse
from students.models import MonthJournal, Student
from ..util import paginate, get_current_group
from django.http import JsonResponse


class JournalView(TemplateView):
	template_name = 'students/journal.html'

	# def post(self, request, *args, **kwargs):
	# 	data = request.POST
	# 	current_date = datetime.strptime(data['date'], '%Y-%m-%d').date()

	# 	month = date(current_date.year, current_date.month, 1)
	# 	present = data['present'] and True or False
	# 	student = Student.objects.get(pk=data['pk'])

	# 	journal = MonthJournal.objects.get_or_create(student=student, date=month)[0]
	# 	setattr(journal, 'present_day%d'%current_date.day, present)
	# 	journal.save()
		
	# 	return JsonResponse({'status':'success'})

	def get_context_data(self, **kwargs):
		context = super(JournalView, self).get_context_data(**kwargs)

		if self.request.GET.get('month'):
			month = datetime.strptime(self.request.GET['month'],'%Y-%m-%d').date()
		else:
			today = datetime.today()
			month = date(today.year, today.month, 1)

		next_month = month + relativedelta(months=1)
		prev_month = month - relativedelta(months=1)
		context['prev_month'] = prev_month.strftime('%Y-%m-%d')
		context['next_month'] = next_month.strftime('%Y-%m-%d')
		context['year'] = month.year
		context['cur_month'] = month.strftime('%Y-%m-%d')
		context['month_verbose'] = month.strftime('%B')
		myear, mmonth = month.year, month.month
		number_of_days = monthrange(myear, mmonth)[1]

		context['month_header'] = [
			{'day':d, 'verbose': day_abbr[weekday(myear, mmonth, d)][:3]}
			for d in range(1, number_of_days+1)]

		if kwargs.get('pk'):
			queryset = [Student.objects.get(pk=kwargs['pk'])]
		else:
			current_group = get_current_group(self.request)
			if current_group:
				queryset = Student.objects.filter(student_group=current_group).order_by('last_name')
			else:
				queryset = Student.objects.all().order_by('last_name')

		update_url = reverse('journal')

		students = []

		for student in queryset:

			try:
				journal = MonthJournal.objects.get(student=student, date=month)
			except Exception:
				journal = None

			days = []
			for day in range(1, number_of_days+1):
				days.append({
					'day':day,
					'present': journal and getattr(journal, 'present_day%d'% day, False)
					or False,
					'date': date(myear, mmonth, day).strftime('%Y-%m-%d'),
					})
			students.append({
				'fullname': u'%s %s' % (student.last_name, student.first_name),
				'days': days,
				'id':student.id,
				'update_url': update_url,
				})

		context = paginate(students, 10, self.request, context, var_name='students')
		return context

	def post(self, request, *args, **kwargs):
		data = request.POST
		if date is None:
		 	return HttpResponse(status=400)

		# # prepare student, dates and presence data
		current_date = datetime.strptime(data['date'], '%Y-%m-%d').date()
		month = date(current_date.year, current_date.month, 1)
		present = data['present'] and True or False
		student = Student.objects.get(pk=data['pk'])

		# # get or create journal object for given student and month
		journal = MonthJournal.objects.get_or_create(student=student, date=month)[0]

		# # set new presence on journal for given student and save result
		setattr(journal, 'present_day%d' % current_date.day, present)
		journal.save()

		# return success status
		return JsonResponse({'status': 'success'})

students/templates/students/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block meta_title %}{% endblock %}</title>
<link rel="stylesheet"
href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="{{ PORTAL_URL }}{% static "css/main.css" %}">


</head>
<body>
	
	<div class="container">
	<!--Header-->
	<div class="row" id="header">
			<div class="col-xs-6">
				<h1>{% trans "Service accounting students" %}</h1>
			</div>

			{% if user.is_authenticated %}
			
			<div class="col-xs-4" id="group-selector">
				<strong>{% trans "Group:" %}</strong>	
				<select>
				<option value="">{% trans "All students" %}</option>
				{% for group in GROUPS %}
				<option value="{{ group.id }}" {% if group.selected %}
					selected = "1"
				{% endif %}>{{ group.title }}</option>
				{% endfor %}
				</select>
			</div>
			
			<div class="col-xs-2" id="user-toolbar">
				<a href="{% url "profile" %}">{{ user.get_full_name|default:user.username}}</a>
				<a href="{% url "users:auth_logout" %}">{% trans "Logout" %}</a>
			</div>
			
			{% else %}
			
			<div class="col-xs-6" id="user-toolbar">
			<a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">{% trans "via Facebook" %}</a> |
				<a href="{% url "users:auth_login" %}">{% trans "Login" %}</a> |
				<a href="{% url "users:registration_register" %}">{% trans "Register" %}</a>
			</div>
			

			{% endif %}
		</div>
	
	<!--End header-->
	<!--Subheader-->
	<div class="row" id="sub-header">
		<div class="col-xs-12">
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation"{% if request.path == '/' or request.path == '/students/'%} class="active"{% endif %}><a href="{% url 'home' %}">{% trans "Students" %}</a></li>
				{% if  user.is_authenticated %}
					
				
				<li role="presentation" {% if request.path == '/journal/'%} class="active"{% endif %}><a href="{% url 'journal' %}">{% trans "Visiting" %}</a></li>
				<li role="presentation" {% if request.path == '/groups/'%} class="active"{% endif %}><a href="{% url 'groups_list' %}">{% trans "Groups" %}</a></li>
				{% endif %}
				{% if  perms.auth.add_user %}
					
				
				<li role="presentation" {% if '/contact-admin' in request.path%}class="active"{% endif %}><a href="{% url "contact_admin" %}">{% trans "Contact" %}</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
	<!--Start Main Page-->
	<div class="row" id="content-columns">
		<div class="col-xs-12" id="content-column">
			{% block status_message %}
				{% if request.GET.status_message %}
					<div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
				{% endif %}
			{% endblock %}
			

			{% block title %}{%	endblock title %}
			{% block content %}{%	endblock content	%}
			</div>
	</div>
	<!--End main page-->
	<!--Foteer-->
	<div class="row" id="footer">
		<div class="col-xs-12">
			&copy; 2015 {% trans "Sevice accountig students" %}
		</div>
	</div>
	<!--End foter-->
</div>
	<!--End container-->
	<!-- Modal Boilerplate -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel"><!-- --></h4>
			</div>
			<div class="modal-body"><!-- --></div>
			<div class="modal-footer"><!-- --></div>
		</div>
	</div>
</div>
<!-- Javascripts Inclusion -->
	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
	<script src="{% static "js/jquery.cookie.js" %}"></script>
<script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js"></script>
<script src="{% url "django.views.i18n.javascript_catalog" %}"></script>
<script src="{% static "js/main.js" %}"></script>
{% block extra_js %}
{% endblock extra_js %}
</body>
</html>

students/templates/students/groups_list.html
{% extends "students/base.html" %}
{% load i18n %}
{%	block meta_title %} {% trans "Groups" %}{%	endblock	%}
{% load staticfiles %}
{% block title %}<h2>{% trans "Groups" %}</h2>{% endblock title %}

	<!--endsubheader-->
{% block content %}

			<a href="{% url "group_add" %}" class="btn btn-primary">{% trans "Add group" %}</a>
				<div>
				{%	if groups %}
				<table class="table table-hover table-striped">
					<thead>
						<tr>
							<th>№</th>
							<th>{% trans "Title" %}</th>
							<th>{% trans "Steward" %}</th>
							<th>{% trans "Actions" %}</th>
						</tr>
					</thead>
					<tbody>
					{% for group in groups %}
						<tr>
							<td>{{ forloop.counter }}</td>
							<td><a href="{% url "group_edit" group.id %}" title="Edit">{{ group.title }}</a></td>
							<td>{% if group.leader %}
								
							<a href="{% url "students_edit" group.leader.id %}" title="Edit">{{ group.leader.last_name}} {{group.leader.first_name}}</a>
							{% endif %}
							</td>
							<td>
								<div class="dropdown">
									<button class="btn btn-default dropdown-tooggle" type="button" data-toggle="dropdown">{% trans "Action" %}
										<span class="caret"></span>
									</button>
									<ul class="dropdown-menu" role="menu">
									<li role="presentation"><a href="{% url "group_edit" group.id %}" role="menuitem" tabindex="-1">{% trans "Edit" %}</a></li>
									<li role="presentation"><a href="{% url "group_delete" group.id %}" role="menuitem" tabindex="-1">{% trans "Delete" %}</a></li>
									</ul>
								</div>
							</td>
						</tr>
						{% endfor %}					
					</tbody>
				</table>
				{% else %}
				<p>{% trans "Groups not found" %}</p>
				{% endif %}
				</div>

	<!--End main page-->
{%if groups.has_other_pages %}
{% with object_list=groups %}
	{% include "students/pagination.html" %}
{% endwith %}
{% endif %}
{%	endblock content %}

students/templates/students/journal.html
{% extends "students/base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% block meta_title %} {% trans "Journal of visiting" %}{% endblock meta_title %}
{% block title %}<h2>{% trans "Journal" %}</h2>{% endblock title %}

{% block content %}
			{% if not students %}
<div class="alert alert-warning">
{% trans "No student in the database. Please" %}
<a href="{% url "students_add" %}">{% trans "add" %}</a> {% trans "first." %}
</div>
{% else %}
<div class="alert alert-warning">
{% trans "Changes are automatically saved in a log each click in a cell of the table." %}
<span id="ajax-progress-indicator">{% trans "Date saving" %}...</span>
</div>
<p id="journal-nav" class="text-center">
<a href="?month={{ prev_month }}" title="Prev month">&larr;</a>
<!-- TODO: translate month name -->
<strong>{% trans month_verbose %} {{ year }}</strong>
<a href="?month={{ next_month }}" title="Next month">&rarr;</a>
</p>
<table class="table table-hover table-striped table-bordered" id="students-journal">
	<thead>
		<tr class="header">
		<th class="num">#</th>
		<th class="name">{% trans "Student" %}</th>
		{% for day in month_header %}
			<th class="day-header">
			<!-- TODO: translate day name -->
			{% trans day.verbose %}
			<br />
			{{ day.day }}
			</th>
		{% endfor %}
		</tr>
	</thead>
	<tbody>
		{% csrf_token %}
				{% for student in students %}
		<tr>
		<td>
			{% if is_paginated %}
				{{ page_obj.start_index|add:forloop.counter|add:"-1" }}
			{% else %}
				{{ forloop.counter }}
			{% endif %}
		</td>
		<td>
			<a title="Edit" target="_blank" href="{% url "students_edit" student.id %}">
			{{ student.fullname }}
		</a>
		</td>
		{% for day in student.days %}
		<td class="day-box">
			<input type="checkbox" data-student-id="{{ student.id }}" data-date="{{ day.date }}" data-url="{{ student.update_url }}" value="1"{% if day.present %} checked="checked" {% endif %} />
		</td>
		{% endfor %}
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endif %}

{% with object_list=students %}
	{% include "students/pagination.html" %}
{% endwith %}

{% endblock content %}

students/templates/students/pagination.html
{% if is_paginated %}
{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<nav>
  <ul class="pagination">
    <li>
      <a href="?page=1{%if order_by %}&amp;order_by={{ order_by }}{% endif %}{% if reverse %}&amp;reverse={{ reverse }}{% endif %}{% if cur_month %}&amp;month={{ cur_month }}{% endif %}">&laquo;</a>
    </li>
    {% for p in paginator.page_range %}
    <li {% if object_list.number == p %}class="active"{% endif %}>
      <a href="?page={{ p }}{%if order_by %}&amp;order_by={{ order_by }}{% endif %}{% if reverse %}&amp;reverse={{ reverse }}{% endif %}{% if cur_month %}&amp;month={{ cur_month }}{% endif %}">{{ p }}</a>
    </li>
    {% endfor %}
    <li>
      <a href="?page={{ paginator.num_pages }}{%if order_by %}&amp;order_by={{ order_by }}{% endif %}{% if reverse %}&amp;reverse={{ reverse }}{% endif %}{% if cur_month %}&amp;month={{ cur_month }}{% endif %}">
        &raquo;</a>
    </li>
  </ul>
</nav>
{% endwith %}
{% endif %}